### ISSUE TITLE
[BUG] navbar sticky='top' doesn't work in dash 1.10+

### ISSUE THREAD

**Issue by MM-Lehmann** [facultyai/dash-bootstrap-components#376] opened 2020-05-21 14:56 UTC
Since upgrading to dash 1.10+, the `dbc.navbar` option `sticky='top'` does not have an effect anymore. The navbar should stay at the top of the viewport, instead in only stays at the top of the page.
This worked up until dash 1.9 as far as I can tell

**Comment by tcbegley** [comment] 2020-05-22 06:25
Hi @MM-Lehmann 

I tried to reproduce this but was unable to with the following code:

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = html.Div(
    [
        dbc.Alert("This is above the navbar", className="m-5"),
        dbc.Navbar(
            [
                dbc.NavbarBrand("Test"),
                dbc.Nav([dbc.NavLink("Item 1"), dbc.NavLink("Item 2")]),
            ],
            sticky="top",
        ),
        html.Div(style={"height": "50vh", "backgroundColor": "red"}),
        html.Div(style={"height": "50vh", "backgroundColor": "yellow"}),
        html.Div(style={"height": "50vh", "backgroundColor": "green"}),
        html.Div(style={"height": "50vh", "backgroundColor": "blue"}),
    ]
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

Can you try that out? If it works, can you see if you can reproduce the behaviour you're seeing with an example?

For reference, I ran that example with

```
dash                      1.12.0
dash-bootstrap-components 0.10.0
dash-core-components      1.10.0
dash-html-components      1.0.3
dash-renderer             1.4.1
dash-table                4.7.0
```

**Comment by MM-Lehmann** [comment] 2020-05-27 06:29
Your example works.
Mine does now too. Strangely, a simple `html.Div(...)` I had been wrapping the navbar in was responsible for the misbehaviour. somehow, the sticky didn't get passed through.
My layout was looking the following:
```
controls = dbc.Row([...])
navbar = html.Div(dbc.Navbar([...]))
graphs = html.Div([...])
modals = html.Div([...])
extras = html.Div([...])
layout = dbc.Container([navbar, controls, graphs, modals, extra], fluid=True)
```

When changing to `navbar = dbc.Navbar([...])` the issue went away.

**Comment by tcbegley** [comment] 2020-05-27 07:39
Ah ok, sticky positioning is relative to the containing block, see [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/position) for more details, so I guess the navbar was being stickily positioned within that div, but since it was the only element in the div that didn't have much affect.

Glad to hear it's working for you now though, going to close this.

**Closed by tcbegley** 2020-05-27 07:39 UTC
