### ISSUE TITLE
Dropdowns in Dash datatable do not appear with Bootstrap

### ISSUE THREAD

**Issue by jimbroze** [facultyai/dash-bootstrap-components#303] opened 2020-01-16 10:53 UTC
- dash version: `#1.4.1`
- dash-bootstrap-components version: `#0.8.1`
- components affected by bug: Dash_table.datatable (but only when using dash-bootstrap-components)

### What is happening?

Dropdowns within dash core components datatables do not show the list of available options.

### What should be happening?

Dropdown list should appear upon clicking

### Code

```python
detailsID = ["productID", "description", "qty", "unitPrice"]
detailsValue = ["Product", "Description", "Qty", "Price"]
detailsType = ["any", "any", "numeric", "numeric"]
detailsColumns = [
    {"id": iD, "name": value, "type": dType}
    for (iD, value, dType) in zip(detailsID, detailsValue, detailsType)
]
detailsColumns[0]["presentation"] = "dropdown"
productList = [{"label": "prod1", "value": "1"}, {"label": "prod2", "value": "2"}]

detailsTableInput = dbc.FormGroup(
    [
        dbc.Label("Purchase item details", html_for="new-purchase-details"),
        dash_table.DataTable(
            id="new-purchase-details",
            columns=detailsColumns,
            data=[dict(**{iD: "" for iD in detailsID})],
            editable=True,
            dropdown={detailsID[0]: {"options": productList}},
        ),
    ]
)
```
A CSS fix was shown in  [this](https://github.com/plotly/dash-table/issues/221#issuecomment-455479720) issue raised in the dash repo. Would it be possible to add it to dash-bootstrap-components?

`
.Select-menu-outer {
  display : block !important;
}
`

**Comment by tcbegley** [comment] 2020-01-18 07:24
Hey @jimbroze,

Thanks for reporting. I believe the issue is that `DataTable` uses some fairly generic CSS class names for styling such as `row` which clash with Bootstrap CSS classes.

I'm reluctant to include CSS in dash-bootstrap-components which restyles components in a different library whose development I am not involved in. Because I don't have control over the implementation of the dropdown, any changes there could break this fix, and then our libraries have to be kept in sync and we would need to declare specific versions of `dash_table` as dependencies. It's quite brittle.

Instead I think the right thing to do is to raise this issue on the `dash_table` repo, and ask them if they can add `display: block` as an inline style or similar. The fact that at the moment the Dropdown breaks if Bootstrap CSS is linked should be reason enough for them to consider it, since Bootstrap is a widely used framework.

What I will do though, is document this fix. I'm in the process of reorganising our documentation, and I'd like to add an FAQs or Troubleshooting page, something like that. This issue and the workaround would be good additions there I think. Is that a reasonable compromise?

**Comment by jimbroze** [comment] 2020-01-18 17:35
Hi @tcbegley,
That seems like a fair compromise, I'll raise it in dash_table and link to this issue for traceability.

Thanks a lot for the response and consideration.

**Comment by tcbegley** [comment] 2020-01-28 23:08
I'm going to close this issue for now since I don't think there's really anything we can do at our end, but feel free to reopen if you have further thoughts / questions.

**Closed by tcbegley** 2020-01-28 23:08 UTC

**Comment by alejandrovalde** [comment] 2021-03-06 14:00
Hi @tcbegley,
Using
dash version: #1.19.0
dash-table version: #4.11.2
dash-bootstrap-components version: #0.11.3

I can't get dropdowns to work in dash tables. Not even adding the CSS
`.Select-menu-outer { display : block !important; }
`
Is there a way to get them to work...?

**Comment by tcbegley** [comment] 2021-03-07 07:53
Hey @alejandrovalde 

Thanks for reporting. I notice the same problem, but in my case the CSS fix _does_ work. Can you share some code that reproduces the problem? Here's the code and versions of Dash libraries I used.

```
dash                      1.19.0
dash-bootstrap-components 0.11.3
dash-core-components      1.15.0
dash-html-components      1.1.2
dash-renderer             1.9.0
dash-table                4.11.2
```

```
.
├── app.py
└── assets
    └── style.css
```

```python
# app.py
from collections import OrderedDict

import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
import dash_table
import pandas as pd

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

df = pd.DataFrame(
    OrderedDict(
        [
            ("climate", ["Sunny", "Snowy", "Sunny", "Rainy"]),
            ("temperature", [13, 43, 50, 30]),
            ("city", ["NYC", "Montreal", "Miami", "NYC"]),
        ]
    )
)


app.layout = html.Div(
    [
        dash_table.DataTable(
            id="table-dropdown",
            data=df.to_dict("records"),
            columns=[
                {
                    "id": "climate",
                    "name": "climate",
                    "presentation": "dropdown",
                },
                {"id": "temperature", "name": "temperature"},
                {"id": "city", "name": "city", "presentation": "dropdown"},
            ],
            editable=True,
            dropdown={
                "climate": {
                    "options": [
                        {"label": i, "value": i}
                        for i in df["climate"].unique()
                    ]
                },
                "city": {
                    "options": [
                        {"label": i, "value": i} for i in df["city"].unique()
                    ]
                },
            },
        ),
        html.Div(id="table-dropdown-container"),
    ]
)


if __name__ == "__main__":
    app.run_server(debug=True)
```

```css
.Select-menu-outer {
  display: block !important;
}
```
