### ISSUE TITLE
Examples on Callbacks using DBC Dropdown

### ISSUE THREAD

**Issue by mdylan2** [facultyai/dash-bootstrap-components#141] opened 2019-03-04 10:57 UTC
I like the style of the DBC Dropdowns compared to the DCC ones. However, the DCC dropdowns display the dropdown item I selected. Was wondering if this feature could be styled into the Bootstrap dropdowns?

Also, it's a little difficult to understand (from the Bootstrap documentation) how a dropdown menu selection can be used to filter graphical information. Would I need to design callbacks on multiple input dropdown menu components using their id property? If you could provide an example on filtering data using callbacks with dropdowns, that would be great!

Otherwise, I really love this project and the work you guys are doing. You're really making designing data dashboards a lot easier for beginners like me!

**Comment by tcbegley** [comment] 2019-03-04 21:00
Hey @mdylan2

Really glad you're enjoying *dash-bootstrap-components*!

The look of `dcc.Dropdown` can be customised quite a bit if you write some custom CSS. What is it about the style of the Bootstrap dropdowns you like specifically? I might be able to give you a few pointers.

>Would I need to design callbacks on multiple input dropdown menu components using their id property?

Yes, that's correct. Though I would say that `dbc.DropdownMenu` works better for navigation type interactions. It's very good for adding a number of links without cluttering up the layout. You could use it for filtering a graph, but I think the `dcc.Dropdown` is better for this, not least because you can see what was selected. That said, here's an example of how you could use `dbc.DropdownMenu`. It uses `dash.callback_context` to figure out which `dbc.DropdownMenuItem` was clicked. This is new in version 0.38 of Dash, so make sure the version that you're using is up to date.

```python
import dash
import dash_bootstrap_components as dbc
import dash_core_components as dcc
import pandas as pd
import plotly.graph_objs as go
from dash.dependencies import Input, Output


labels = ["Oxygen", "Hydrogen", "Carbon_Dioxide", "Nitrogen"]
values = [4500, 2500, 1053, 500]

trace = go.Pie(labels=labels, values=values)

data = pd.DataFrame(
    {
        "item": [
            "Red square",
            "Red circle",
            "Blue square",
            "Blue circle",
            "Green square",
            "Green circle",
        ],
        "color": ["red", "red", "blue", "blue", "green", "green"],
        "shape": ["square", "circle", "square", "circle", "square", "circle"],
        "qty": [3, 2, 5, 3, 2, 6],
    }
)

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.DropdownMenu(
            [
                dbc.DropdownMenuItem("All", id="all"),
                dbc.DropdownMenuItem(divider=True),
                dbc.DropdownMenuItem("Color", header=True),
                dbc.DropdownMenuItem("Red", id="red"),
                dbc.DropdownMenuItem("Blue", id="blue"),
                dbc.DropdownMenuItem("Green", id="green"),
                dbc.DropdownMenuItem(divider=True),
                dbc.DropdownMenuItem("Shape", header=True),
                dbc.DropdownMenuItem("Square", id="square"),
                dbc.DropdownMenuItem("Circle", id="circle"),
            ],
            label="Filter plot",
            className="mb-3",  # add bottom margin
        ),
        dcc.Graph(id="graph"),
    ]
)


@app.callback(
    Output("graph", "figure"),
    [
        Input("all", "n_clicks"),
        Input("red", "n_clicks"),
        Input("blue", "n_clicks"),
        Input("green", "n_clicks"),
        Input("square", "n_clicks"),
        Input("circle", "n_clicks"),
    ],
)
def make_graph(*args):
    ctx = dash.callback_context

    if not ctx.triggered:
        button_id = "all"
    else:
        button_id = ctx.triggered[0]["prop_id"].split(".")[0]

    if button_id in ["red", "blue", "green"]:
        df = data.loc[data["color"] == button_id, :]
    elif button_id in ["square", "circle"]:
        df = data.loc[data["shape"] == button_id, :]
    else:
        df = data

    return go.Figure(data=[go.Pie(labels=df["item"], values=df["qty"])])


if __name__ == "__main__":
    app.run_server()
```

**Comment by mdylan2** [comment] 2019-03-05 04:27
Hi @tcbegley,

Thanks for the quick response. I think I'll stick to the `dcc.Dropdown` to filter my graphs for now.  

> What is it about the style of the Bootstrap dropdowns you like specifically?

I've been working on the CSS for my dropdown and have come a long way with it. So far, I've been able to decrease the font-size of the placeholder and the border colors (before and after selection). I'm struggling with reducing the actual size of the box (specifically the height of the box) and the font-size of the dropdown elements. I'm trying to mimic Bootstrap's small dropdown size. If you could provide some tips, that would be great!

I also have one other question related to styling a bootstrap dropdown I included in my NavBar. Here's my NavBar code:

```
import dash_bootstrap_components as dbc

navbar = dbc.NavbarSimple(
    children=[
        dbc.NavItem(dbc.NavLink("Overview",href = "/apps/dashboard")),
        dbc.DropdownMenu(
            nav=True,
            in_navbar=True,
            label="Analytical Tools",
            children=[
                        dbc.DropdownMenuItem(dbc.NavLink("Student Performance Tracker", href="/apps/comparison")), 
                        dbc.DropdownMenuItem(dbc.NavLink("Analytical Tool 2", href="#")),
                        dbc.DropdownMenuItem(dbc.NavLink("Analytical Tool 3",href="#")),
                ],
        ),
        dbc.NavItem(dbc.NavLink("Feedback",href = "/apps/feedback")),
        dbc.NavItem(dbc.NavLink("Support",href = "#"))        
    ],
    brand="Dashboard",
    brand_href="#",
    sticky="top",
    dark = True,
    color = 'primary'
)
```

I want to mimic the style of the Flatly Navbar (preview from their website included below) and so I downloaded the `bootstrap.css` file from [your Github](https://github.com/thomaspark/bootswatch/tree/master/dist/flatly). `bootstrap.min.css` didn't contain the styling for the NavBar of interest.

![image](https://user-images.githubusercontent.com/47123837/53780591-1df12f80-3f2b-11e9-8f38-eed4b1b16c4e.png)

My issue is this (images below): when I click on the `dbc.DropdownMenu`, the dropdown is all white. Only when I scroll over the menu item does the color turn dark. Furthermore, the color of the text only changes to green when I scroll over the text itself (and not the menu item as a whole). How do I fix these issues? I'm mainly afraid that the CSS changes I'll make will affect the rest of my code. Do you have any suggestions for what classNames I should be applying CSS to?

![image](https://user-images.githubusercontent.com/47123837/53780991-e1bece80-3f2c-11e9-8d24-be3661c58847.png)

**Cursor not hovering over text:**
![image](https://user-images.githubusercontent.com/47123837/53781008-f8652580-3f2c-11e9-9cc9-1b14b2f7c9a9.png)




Sorry for asking so many questions!

**Comment by tcbegley** [comment] 2019-03-05 08:05
Hey @mdylan2 

I'll have a play around with the styling of `dcc.Dropdown` and let you know if I get anywhere.

For your second question, the white color of the links is being set by `dbc.NavLink`, just delete these and it should look ok again, i.e.

```python
dbc.DropdownMenu(
    nav=True,
    in_navbar=True,
    label="Analytical Tools",
    children=[
        dbc.DropdownMenuItem("Student Performance Tracker", href="/apps/comparison"),
        dbc.DropdownMenuItem("Analytical Tool 2", href="#"),
        dbc.DropdownMenuItem("Analytical Tool 3", href="#"),
    ],
)
```

You only need the `NavLink` for items like "Overview", "Feedback" etc.

Also as a final note, if you want to use flatly, you don't need to download anything, you can just do this

```python
app = dash.Dash(external_stylesheets=[dbc.themes.FLATLY])
```

**Comment by mdylan2** [comment] 2019-03-07 09:42
Really helpful advice! Thanks a lot @tcbegley!

Please let me know if you figure anything out about the `dcc.Dropdown` height.

**Comment by usser123** [comment] 2019-10-04 01:03
I am also having the issue with dcc.Dropdown height. I have been able to use optionHeight for setting the cell height. However the height of the Dropdown container itself has been really hard to set. 

@mdylan2 did you manage to find out how to set the dcc.Dropdown height ?

**Comment by tcbegley** [comment] 2019-10-15 06:36
Hey @usser123,

Sorry for the slow response, I was travelling with limited internet access the last couple weeks.

Unfortunately what I've found looking into this is that it's really hard to change the height of the Dropdown, at least if you want to make it larger. The reason is that the Dropdown is powered by a component called [react-virtualized-select](https://github.com/bvaughn/react-virtualized-select). Virtualized means that if you have lots of options in the dropdown, it doesn't load all of them at once, it loads them intelligently as you scroll through the options. The problem is that if you write some CSS to make the box bigger, the underlying javascript is still assuming it only needs to render as many options as would fill the original sized box. So you end up just revealing whitespace.

For example, at first things look good:

![image](https://user-images.githubusercontent.com/15220906/66805885-0dbc1c80-ef1e-11e9-82d1-d9ca85de50b9.png)

Then when you scroll up:

![image](https://user-images.githubusercontent.com/15220906/66805933-288e9100-ef1e-11e9-9065-e1303e6834be.png)

For that reason, I think that changing the size of the box would require some changes to the underlying javascript, not just some custom CSS. You could try raising an issue on _dash-core-components_ repo and see if they are able to add a new prop that would let you control the height of the dropdown?

**Comment by tcbegley** [comment] 2019-10-20 18:03
I'm going to close this now, unfortunately there's not much we can do about the `dcc.Dropdown`  window height just with CSS. Any feature suggestions for that component are probably better directed at the _dash-core-components_ devs.

Any new issues with `DropdownMenu`, please do feel free to open up a new issue.

**Closed by tcbegley** 2019-10-20 18:03 UTC

**Comment by divyarathi1** [comment] 2020-10-19 23:20
To answer the very first question in the thread asked by @mdylan2:

_However, the DCC dropdowns display the dropdown item I selected. Was wondering if this feature could be styled into the Bootstrap dropdowns?_

Had a similar issue and tried to work on it.
Following is how the label displayed on the dbc dropdown can be changed to match the value selected in the dbc dropdown.
1. Create an id for the dropdownmenu. 
2. Use that id as an Output element in the next graph callback. So if the one of the menu options is chosen, the label of the dropdown will change accordingly and so will the graph. If the dropdown menu is not opened (ctx not triggered) then the default label 'all' will be shown and the related graph for 'all' displayed.

(Copying example by @tcbegley to modify it. Note that my additions are followed with comments. Rest of the example is same.)
Hope this helps someone!!



```
app.layout = dbc.Container(
    [
        dbc.DropdownMenu(
            [
                dbc.DropdownMenuItem("All", id="all"),
                dbc.DropdownMenuItem(divider=True),
                dbc.DropdownMenuItem("Color", header=True),
                dbc.DropdownMenuItem("Red", id="red"),
                dbc.DropdownMenuItem("Blue", id="blue"),
                dbc.DropdownMenuItem("Green", id="green"),
                dbc.DropdownMenuItem(divider=True),
                dbc.DropdownMenuItem("Shape", header=True),
                dbc.DropdownMenuItem("Square", id="square"),
                dbc.DropdownMenuItem("Circle", id="circle"),
            ],
            label="Filter plot",
            className="mb-3", 
            id= 'iddropdownmenu'  #create an id for the dropdown menu to be used in the graph callback to modify the label
        ),
        dcc.Graph(id="graph"),
    ]
)


@app.callback(
   [ Output("graph", "figure"),
     Output("iddropdownmenu", "label")  # using the id for the dropdown menu as an output to modify its label when callback is triggered
    [
        Input("all", "n_clicks"),
        Input("red", "n_clicks"),
        Input("blue", "n_clicks"),
        Input("green", "n_clicks"),
        Input("square", "n_clicks"),
        Input("circle", "n_clicks"),
    ],
)
def make_graph(*args):
    ctx = dash.callback_context

    if not ctx.triggered:
        button_id = "all"
    else:
        button_id = ctx.triggered[0]["prop_id"].split(".")[0]

    if button_id in ["red", "blue", "green"]:
        df = data.loc[data["color"] == button_id, :]
    elif button_id in ["square", "circle"]:
        df = data.loc[data["shape"] == button_id, :]
    else:
        df = data

    return go.Figure(data=[go.Pie(labels=df["item"], values=df["qty"])]), button_id 

# the second output being returned above is the selected button_id (all, red, blue, green, etc...) which will be set as the label for the dropdownmenu


if __name__ == "__main__":
    app.run_server()
```
