### ISSUE TITLE
Switching tabs on button click

### ISSUE THREAD

**Issue by jfrank87** [facultyai/dash-bootstrap-components#212] opened 2019-05-26 15:22 UTC
Dear community,

Once again, thank you for the great work on this software!

I am building an app that contains several tabs. 
I want to include a button that on click will activate another tab.
The documentation contains hints on how to go about this, but unfortunately I can't get it to work. I provided a stripped-down example below. 

```
#!/usr/bin/env python3

import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = html.Div([

    dbc.Tabs(id="tabs", active_tab="tab-0", children=[
        dbc.Tab(id="tab_1", label="Tab 1", children=[
            dbc.Container([
                html.P("Content Tab 1"),
                dbc.Button(id="button_tab_1", children="Goto Tab 2")
            ], fluid=True),
        ]),
        dbc.Tab(id="tab_2", label="Tab 2", children=[
            dbc.Container([
                html.P("Content Tab 2")
            ], fluid=True)
        ])
    ])
])

@app.callback(
    # Button: switch to Tab 2
    Output("tabs", "active_tab"),
    [Input("button_tab_1", "n_clicks")])
def tab_resources(click):
    if click:
        return "tab_2"

app.run_server(debug=True)
```

The callback seems to work; the number of button clicks are registered, but the app does not switch to the other tab. What am I missing? Any help is greatly appreciated. Thanks!

Jeroen

**Comment by tcbegley** [comment] 2019-05-31 20:28
Hi @jfrank87 

Thanks for reporting, and sorry for being slow to respond to you. I don't think you're missing anything, the `Tabs` component will set the `active_tab` prop when a different tab is selected, but not vice versa. I think it should be possible to change that, then your code snippet should work as you expected it to.

**Comment by tcbegley** [comment] 2019-06-01 20:00
Hey @jfrank87 

I just opened #213 to address this. You can try out the changes by installing the prerelease:

```
pip install dash-bootstrap-components==0.6.2rc1
```

If you have a chance to test it out and let me know how you get on that would be much appreciated. It's working at my end, with a few minor changes to your code:
1) You need to specify `tab_id` rather than `id` for each of the `Tab` components.
2) Set `active_tab` of the `Tabs` component to be one of these two `tab_id`s, or leave it unspecified. `tab-0` doesn't actually exist in your layout.

Here's your code with those changes for convenience:

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = html.Div([
    dbc.Tabs(id="tabs", active_tab="tab_1", children=[
        dbc.Tab(tab_id="tab_1", label="Tab 1", children=[
            dbc.Container([
                html.P("Content Tab 1"),
                dbc.Button(id="button_tab_1", children="Goto Tab 2")
            ], fluid=True),
        ]),
        dbc.Tab(tab_id="tab_2", label="Tab 2", children=[
            dbc.Container([
                html.P("Content Tab 2")
            ], fluid=True)
        ])
    ])
])

@app.callback(
    # Button: switch to Tab 2
    Output("tabs", "active_tab"),
    [Input("button_tab_1", "n_clicks")])
def tab_resources(click):
    if click:
        return "tab_2"

app.run_server(debug=True)
```

**Comment by jfrank87** [comment] 2019-06-03 07:55
Hey @tcbegley 

Thanks for the _quick_ response. Awesome you've already found the time to implemented this functionality! I did some testing and can confirm the tabs are now switching following a button click. Nice!

A minor detail: when switching from tab N to tab N+1, tab N+1 is shown at the same scrolling position as tab N. If for example someone scrolls to the bottom of a long page and switches to a different tab, the new tab is shown at the bottom position as well. It would be nice (but not essential to me) to have the now tab start from the top.

Side note: you are correct, `tab-0` does not exist in the layout. I'm referring to the tab by its index. This is described in the documentation for the `Tabs` component:
> active_tab (string, optional): Determine which tab is currently showing. Will be the id of the tab or 'tab-i' where i is the index of the tab (indexed from zero)

This doesn't seem to work right now (perhaps I am misunderstanding the docs). 

Thanks a lot!

**Comment by tcbegley** [comment] 2019-06-03 08:07
Oh good catch, I think the docstring is just wrong. Should be something like:

> Will be the `tab_id` of the tab of `tab-i` where i is the index of the tab (indexed from zero) if `tab_id` is not specified.

I'll add that as a change to the pull request.

**Comment by tcbegley** [comment] 2019-06-03 16:27
Hey @jfrank87 

I managed to recreate the scrolling issue you describe. The issue is React trying to be smart and preserve details when rendering the different tab contents. You can fix it by setting the `key` of the tab content container when the tabs are switched, which effectively tells React to completely re-render that component.

Here's a rough example, let me know if it doesn't make sense:

```python
app.layout = html.Div([
    dbc.Tabs(..., id="tabs"),
    html.Div(id="tab-content"),
])

@app.callback(
    [Output("tab-content", "key"), Output("tab-content", "children")],
    [Input("tabs", "active_tab")],
)
def render_tab(at):
    if at == "tab-0":
        return at, tab_0_content
    elif at == "tab-1":
        return at, tab_1_content
```

**Comment by tcbegley** [comment] 2019-06-05 22:15
This is now available in version 0.6.2.

@jfrank87 give me a shout if you have further issues with the scrolling, but I'm going to close this for now.

**Closed by tcbegley** 2019-06-05 22:15 UTC

**Comment by ndepal** [comment] 2020-05-13 21:31
Sorry to be posting on an old issue but I have the same scrolling problem as @jfrank87. On a big tab I scroll down and click a button that takes me to a new tab and I would like the page to be scrolled to the top.

I create my tabs slightly differently, so I'm not sure which element's `key` I should be setting.

Here is my layout:
```
layout = html.Div(
    [
        daq.DarkThemeProvider(
            html.Div([
                dbc.Tabs(
                    [
                        dbc.Tab(id='overview-tab', label='Overview', tab_id='overview', children=app1.layout),
                        dbc.Tab(id='details-tab', label='Details', tab_id='details', children=app2.layout, disabled=True),
                    ],
                    id='tabs',
                    active_tab='overview',
                ),
            ]),
            theme=theme,
        )
    ],
)
```

I then have a callback that sets the `Output('tabs', 'active_tab')` in order to switch to the `'details'` tab.

Where should I be setting the `key`? And does it matter whether the value I set for it is different from the one I set previously?

**Comment by tcbegley** [comment] 2020-05-14 07:40
Hi @ndepal 

When using `Tabs` as you are (i.e. passing tabs as children rather than rendering with a callback), the key is managed for you, so you can't resolve this by setting the key.

I think the best thing might be use a clientside callback, then you can scroll the window with some javascript. Here's an example

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Tabs(
            [
                dbc.Tab(
                    [
                        html.Div(
                            style={
                                "height": "100vh",
                                "background-color": "red",
                            }
                        ),
                        dbc.Button("switch", id="button"),
                    ],
                    label="Overview",
                    tab_id="overview",
                ),
                dbc.Tab(
                    id="details-tab",
                    label="Details",
                    tab_id="details",
                    children=html.Div(
                        style={"height": "100vh", "background-color": "blue",}
                    ),
                ),
            ],
            id="tabs",
        ),
    ],
    className="p-5",
)


app.clientside_callback(
    """
    function(n) {
        if (n && n > 0) {
            // scroll to top
            window.scrollTo(0, 0);
            return "details";
        }
        return "overview";
    }
    """,
    Output("tabs", "active_tab"),
    [Input("button", "n_clicks")],
)


if __name__ == "__main__":
    # note: clientside callbacks seem to break if debug=True
    app.run_server()
```

**Comment by ndepal** [comment] 2020-05-14 16:07
Thanks for the quick reply @tcbegley! This does what I want. It also works if I have `debug=True`, fyi.

**Comment by Rodrigocepeda** [comment] 2022-03-27 15:25
Hello, @tcbegley. I am having the same issue (when I change to a different tab the position of the screen in tab N+1 is the same a in tab N) but it do not have a switch button for switching between tabs, I just press the tab on the top menu for switching between them.
The function would not work for me because I do not have the Input("button","n_clicks") component for the callback. Do you happen to know how could I fix this issue?
Thanks in advance
