### ISSUE TITLE
 dash_bootstrap_components version versus python version

### ISSUE THREAD

**Issue by DSAGRO3F** [facultyai/dash-bootstrap-components#993] opened 2024-01-04 17:48 UTC
Hi, I am using python 3.12, I installed  dash-bootstrap-components (1.5.0 v.) package using pip3.12 in my virtual environment, then imported  dash_bootstrap_components. Error message saying no  module named  dash_bootstrap_components ,
So I wonder if  dash_bootstrap_components  1.5.0 v. is compatible with python 3.12 ?

**Comment by tcbegley** [comment] 2024-01-04 20:05
Hi @DSAGRO3F 

It is compatible, I just installed in a fresh 3.12 environment myself and successfully ran a test app to double check.

The fact that the error says no module named `dash_bootstrap_components` was found suggests that the installation failed. If you didn't see any error messages when installing with `pip`, you should check that `pip` is installing in the same environment as the `python` command you are running the app with. Run`which python` and `which pip` if you're on macOS / Linux to check (on windows try `where python` in command prompt or `Get-Command python` in PowerShell).

You also have the option of installing with `python -m pip install dash-bootstrap-components` which ensures that the module will be installed in whatever environment `python` command is referencing.

**Comment by DSAGRO3F** [comment] 2024-01-04 23:17
Many thanks for your answer,

Good to hear that python 3.12 and dash_bootstrap_components are compatible,

I followed your advice …
(env) ***@***.*** other_dash_apps % which python3.12
/Users/olivierdebeyssac/Python_plotly_dash/other_dash_apps/env/bin/python3.12

(env) ***@***.*** other_dash_apps % which pip3.12
/Users/olivierdebeyssac/Python_plotly_dash/other_dash_apps/env/bin/pip3.12


Seems pip and python are installed in same environment 



Also tried:
(env) ***@***.*** other_dash_apps % python3.12 -m pip install dash-bootstrap-components
Requirement already satisfied: dash-bootstrap-components in ./env/lib/python3.12/site-packages (1.5.0)

Output of installation confirms it is installed.



Confirmed by pip list that says it is installed in my virtual environment 

(env) ***@***.*** other_dash_apps % pip3.12 list
Package                   Version
------------------------- ------------
ansi2html                 1.9.1
blinker                   1.7.0
certifi                   2023.11.17
charset-normalizer        3.3.2
click                     8.1.7
contourpy                 1.2.0
cycler                    0.12.1
dash                      2.14.2
dash-bootstrap-components 1.5.0
dash-core-components      2.0.0
dash-html-components      2.0.0




(env) ***@***.*** other_dash_apps % pip3.12 show dash-bootstrap-components
Name: dash-bootstrap-components
Version: 1.5.0
Summary: Bootstrap themed components for use in Plotly Dash
Home-page: https://dash-bootstrap-components.opensource.faculty.ai/
Author: Faculty
Author-email: ***@***.***
License: Apache Software License
Location: /Users/olivierdebeyssac/Python_plotly_dash/other_dash_apps/env/lib/python3.12/site-packages



From all this I come to the conclusion that it is installed correctly. But looking at package list installed in project environment in Pycharm, I see that dash-bootstrap-components is not installed….

Hard to understand for now ….

If any idea to fix it, I would appreciate 


Thanks


Olivier,

**Comment by DSAGRO3F** [comment] 2024-01-04 23:21
I tried different things to see if installation is made the proper way...


(env) olivierdebeyssac@macbook-air-m1-olivier other_dash_apps % which python3.12
/Users/olivierdebeyssac/Python_plotly_dash/other_dash_apps/env/bin/python3.12

(env) olivierdebeyssac@macbook-air-m1-olivier other_dash_apps % which pip3.12
/Users/olivierdebeyssac/Python_plotly_dash/other_dash_apps/env/bin/pip3.12


Seems pip and python are installed in same environment 



Also tried:
(env) olivierdebeyssac@macbook-air-m1-olivier other_dash_apps % python3.12 -m pip install dash-bootstrap-components
Requirement already satisfied: dash-bootstrap-components in ./env/lib/python3.12/site-packages (1.5.0)

Output of installation confirms it is installed.



Confirmed by pip list that says it is installed in my virtual environment 

(env) olivierdebeyssac@macbook-air-m1-olivier other_dash_apps % pip3.12 list
Package                   Version
------------------------- ------------
ansi2html                 1.9.1
blinker                   1.7.0
certifi                   2023.11.17
charset-normalizer        3.3.2
click                     8.1.7
contourpy                 1.2.0
cycler                    0.12.1
dash                      2.14.2
dash-bootstrap-components 1.5.0
dash-core-components      2.0.0
dash-html-components      2.0.0




(env) olivierdebeyssac@macbook-air-m1-olivier other_dash_apps % pip3.12 show dash-bootstrap-components
Name: dash-bootstrap-components
Version: 1.5.0
Summary: Bootstrap themed components for use in Plotly Dash
Home-page: https://dash-bootstrap-components.opensource.faculty.ai/
Author: Faculty
Author-email: [opensource@faculty.ai](mailto:opensource@faculty.ai)
License: Apache Software License
Location: /Users/olivierdebeyssac/Python_plotly_dash/other_dash_apps/env/lib/python3.12/site-packages

**Comment by tcbegley** [comment] 2024-01-05 07:50
Thanks for the extra detail. Sounds to me that the issue is your PyCharm project environment is not the same as the virtual environment you have been installing packages in.

I don't use PyCharm myself so I'm afraid I can't help there, but that's where I would start.

**Comment by DSAGRO3F** [comment] 2024-01-05 08:52
Hi TomMany thanks for your help!the super treacherous thing is that I have three Python 3.12 environments and I probably imported dash-bootstrap-components into one of the other two environments other than pycharm…I solved the problem Thanks again Olivier Envoyé de mon iPhoneLe 5 janv. 2024 à 08:50, Tom Begley ***@***.***> a écrit :﻿
Thanks for the extra detail. Sounds to me that the issue is your PyCharm project environment is not the same as the virtual environment you have been installing packages in.
I don't use PyCharm myself so I'm afraid I can't help there, but that's where I would start.

**Closed** 2024-01-05 09:47 UTC
Labels: upstream
