### ISSUE TITLE
spinner size

### ISSUE THREAD

**Issue by richlegrand** [facultyai/dash-bootstrap-components#577] opened 2021-05-07 14:15 UTC
When specifying the size of the spinner through spinner_style, it doesn't change the size of the spinner.

 spinner_style={"width": "5rem", "height": "5rem"}

Specifying size though size works:

size="sm"

but there is no difference between "md" and "lg".  

This worked in previous versions of dash bootstrap.  I'm using version 0.12.2.  I don't know the previous version numbers that worked.  

thanks

**Comment by tcbegley** [comment] 2021-05-07 16:52
Hey @richlegrand, thanks for reporting and sorry for the regression.

I have just merged #578 which resolves the bug and also adds a number of tests so that hopefully the same problem won't happen again. The fix will make it into the next release of dash-bootstrap-components. Since we only just released a new version this probably won't happen immediately, but you can use the pre-release I just made

```
pip install dash-bootstrap-components==0.12.3a1
```

Alternatively, you can still set the size of the spinner with a little custom CSS like in the following example

```python
import dash
import dash_bootstrap_components as dbc

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    dbc.Spinner(color="primary"), className="p-5 large-spinner"
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

```css
.large-spinner .spinner-border {
  width: 5rem;
  height: 5rem;
}
```

BTW, there actually is no `lg` spinner in Bootstrap, there was an error in the docstring which I also fixed in #578.

**Comment by richlegrand** [comment] 2021-05-07 19:39
whoa, that was really quick -- thanks!

**Comment by tcbegley** [comment] 2021-07-31 12:51
Sorry for the delay making a full release, this is now resolved.

**Closed by tcbegley** 2021-07-31 12:51 UTC
