### ISSUE TITLE
Support dash 1.11 wildcard ids/callbacks

### ISSUE THREAD

**Issue by MM-Lehmann** [facultyai/dash-bootstrap-components#361] opened 2020-05-04 13:48 UTC
I would like to use dash's 1.11 introduced feature of wildcard callbacks with the bootstrap components. What is needed on your side to support that feature?
see https://dash.plotly.com/pattern-matching-callbacks

**Comment by tcbegley** [comment] 2020-05-05 06:44
Hi @MM-Lehmann,

As far as I'm aware there's no changes needed from us. The examples in the Dash documentation appear to work if you adapt them for use with dash-bootstrap-components. Is there something you tried to achieve that didn't work? Please let me know if so.

Here's some examples for you to try out. First, adapted from the second example in the docs

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import MATCH, Input, Output, State

app = dash.Dash(
    suppress_callback_exceptions=True,
    external_stylesheets=[dbc.themes.BOOTSTRAP],
)

app.layout = html.Div(
    [
        html.Button("Add Filter", id="dynamic-add-filter", n_clicks=0),
        html.Div(id="dynamic-select-container", children=[]),
    ]
)


@app.callback(
    Output("dynamic-select-container", "children"),
    [Input("dynamic-add-filter", "n_clicks")],
    [State("dynamic-select-container", "children")],
)
def display_selects(n_clicks, children):
    new_element = html.Div(
        [
            dbc.Select(
                id={"type": "dynamic-select", "index": n_clicks},
                options=[
                    {"label": i, "value": i}
                    for i in ["NYC", "MTL", "LA", "TOKYO"]
                ],
            ),
            html.Div(id={"type": "dynamic-output", "index": n_clicks}),
        ]
    )
    children.append(new_element)
    return children


@app.callback(
    Output({"type": "dynamic-output", "index": MATCH}, "children"),
    [Input({"type": "dynamic-select", "index": MATCH}, "value")],
    [State({"type": "dynamic-select", "index": MATCH}, "id")],
)
def display_output(value, id):
    return html.Div("Select {} = {}".format(id["index"], value))


if __name__ == "__main__":
    app.run_server(debug=True)
```

And one that I made while experimenting

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import MATCH, Input, Output, State

app = dash.Dash(
    external_stylesheets=[dbc.themes.BOOTSTRAP],
    suppress_callback_exceptions=True,
)

app.layout = dbc.Container(
    [
        dbc.Button("Add collapse", id="add"),
        html.Div([], id="collapse-container"),
    ],
    className="p-5",
)


@app.callback(
    Output("collapse-container", "children"),
    [Input("add", "n_clicks")],
    [State("collapse-container", "children")],
)
def add_collapse(n, children):
    if n:
        children.append(
            html.Div(
                [
                    dbc.Button(
                        f"Toggle collapse {n}",
                        id={"type": "toggle", "index": n},
                        key=f"button-{n}",
                    ),
                    dbc.Collapse(
                        f"Collapse {n} contents",
                        id={"type": "collapse", "index": n},
                        key=f"collapse-{n}",
                    ),
                ],
                className="m-3",
            )
        )
    return children


@app.callback(
    Output({"type": "collapse", "index": MATCH}, "is_open"),
    [Input({"type": "toggle", "index": MATCH}, "n_clicks")],
    [State({"type": "collapse", "index": MATCH}, "is_open")],
)
def toggle_collapse(n, is_open):
    # make sure the callback is only toggled when the callback fires because
    # the toggle was clicked.
    triggered, _ = dash.callback_context.triggered[0]["prop_id"].split(".", 1)
    if n and triggered:
        return not is_open
    return is_open


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by MM-Lehmann** [comment] 2020-05-05 11:27
Thanks for clarifying. I've been able to use the components in a similar, though more complex environment. However, if I use `id=dict(...)` in `dbc.Tooltip` I get JS errors in my frontend like this:
```
r.removeEventListener is not a function
r.addEventListener is not a function
```
Also, there appeared a few more errors which I haven't been able to trace down as of yet.
It just makes me believe that at some places, strings are still strictly expected instead of dicts.

**Comment by tcbegley** [comment] 2020-05-05 12:27
Ah interesting, thanks for letting me know, I'll take a look and try to track down the source of the bugs when I get a chance.

**Comment by tcbegley** [comment] 2020-05-09 08:48
Hey @MM-Lehmann,

I've looked into this, found the same issue you described above when setting `target=dict(...)` (I assume that's what you mean rather than `id`? I wasn't able to replicate that). The reason for this is that dictionaries that get passed to `id` [now get stringified](https://github.com/plotly/dash/blob/dev/dash/_utils.py#L190-L193) to support the pattern-matching callbacks, but that wasn't happening for dictionaries passed to `target`.

I was able to successfully modify `Tooltip` and `Popover` to stringify targets, but the problem is that the stringified dictionaries look something like `'{"index":1,"type":"div"}'` which is a valid HTML id but contains characters (`:`, `{`, `"` etc.) that mean it's not a valid CSS selector. Under the hood `Tooltip` is using `document.querySelector` to find the element to attach to, and that now fails as a result.

I don't think there's a particularly easy fix to that given the way that IDs are currently stringified. I would suggest that when using `Tooltip` or `Popover` in dynamically generated sections of your app, you add an additional element to use as the target where you more tightly control the `id`. For example, something like

```python
def add_components(n, children):
    if n:
        children.append(
            html.Div(
                [
                    # wrapper with controlled id
                    html.Div(
                        html.Div(id={"type": "div", "index": n}),
                        id=f"tooltip-div-wrapper-{n}",
                    ),
                    dbc.ToolTip(
                        f"The {n}th tooltip", target=f"tooltip-div-wrapper-{n}"
                    ),
                ],
            )
        )
    return children
```

Let me know if that helps.

**Comment by MM-Lehmann** [comment] 2020-05-14 08:25
This could be connected to failing persistence with `id=dict(...)` as reported in #283

**Comment by tcbegley** [comment] 2020-06-09 07:37
Closing this as we support this as much as is possible. The exception is that the `target` attribute of `Tooltip` and `Popover` don't accept a dictionary, however since dictionary ids get serialised to something that is a valid HTML id, but an invalid CSS selector, and those components use `document.querySelector` under the hood, there isn't really much we can do about that. See above for a workaround using a wrapper element with a manually controlled id.

**Closed by tcbegley** 2020-06-09 07:37 UTC

**Comment by MM-Lehmann** [comment] 2020-06-22 06:51
Another exception to add:
`dbc.FormFeedback` and the `valid` class of the `dbc.Input` Components don't seem to work with dict id's either. Strangely enough, the `invalid` property seems to work fine.

**Comment by tcbegley** [comment] 2020-06-22 07:44
Thanks for reporting, if you could post an example I'll look into it.

**Comment by Yook74** [comment] 2020-08-18 19:49
Would be great if this was mentioned in the Tooltip and Popover documentation

**Comment by tcbegley** [comment] 2020-11-30 13:39
@Yook74 added a note on this [here](https://dash-bootstrap-components.opensource.faculty.ai/docs/faq/)
